version: '3.8'

services:
  node19:
    build:
      context: .
    network_mode: "host"
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://127.0.0.1:27017/ChatGpt
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
