version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://localhost:27017/ChatGpt
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    network_mode: host

volumes:
  mongo-data:
